version: "3.9"

services:
  api:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile
    env_file:
      - ../../.env
    command: uvicorn apps.api.main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ../..:/app
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"

  worker:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile
    env_file:
      - ../../.env
    command: python -m apps.workers.scheduler
    volumes:
      - ../..:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: realtor
      POSTGRES_PASSWORD: realtor
      POSTGRES_DB: realtor
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgdata:
