name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: realtor
          POSTGRES_PASSWORD: realtor
          POSTGRES_DB: realtor
        ports: [ '5432:5432' ]
        options: >-
          --health-cmd "pg_isready -U realtor" --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:7-alpine
        ports: [ '6379:6379' ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Lint
        run: |
          black --check .
          isort --check-only .
          flake8
      - name: Run tests
        env:
          DATABASE_URL: postgresql+psycopg2://realtor:realtor@localhost:5432/realtor
          REDIS_URL: redis://localhost:6379/0
        run: pytest
